FROM prom/prometheus

LABEL maintainer="admin@techmanyu.com"

# Add in the configuration file from the local directory.
ADD prometheus.yml /etc/prometheus/prometheus.yml
ADD alert.rules /etc/prometheus/alert.rules