global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets: ['alert-manager:9093']
    scheme: http
    timeout: 10s

# this is where I have simple alert rules
rule_files:
  - /etc/prometheus/alert.rules
  
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - prometheus:9090
- job_name: techmanyu-service
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /prometheus
  scheme: http
  static_configs:
  - targets:
    - techmanyu-service:8080